version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banpay
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/banpay

  flyway:
    image: flyway/flyway
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/banpay -user=user -password=password -connectRetries=60 migrate

volumes:
  postgres_data: